const hotelsData = [
    {
        id: 1,
        img: require('./images/blue.png'),
        name: 'Karethium & Astarte',
        region: 'Jewels of Nizam',
        housing: 'Ps',
        services: 'Bd',
        pool: 'Ba',
        area: '185 m2',
        beach: '500 m',
        period: '20.11.19-31.11.19',
        price: 2800,
    },
    {
        id: 2,
        img: require('./images/blue.png'),
        name: 'Karethium & Astarte',
        region: 'Jewels of Nizam',
        housing: 'Ps',
        services: 'Bd',
        pool: 'Ba',
        area: '185 m2',
        beach: '500 m',
        period: '20.11.19-31.11.19',
        price: 2800,
    },
    {
        id: 3,
        img: require('./images/blue.png'),
        name: 'Karethium & Astarte',
        region: 'Jewels of Nizam',
        housing: 'Ps',
        services: 'Bd',
        pool: 'Ba',
        area: '185 m2',
        beach: '500 m',
        period: '20.11.19-31.11.19',
        price: 2800,
    },
    {
        id: 4,
        img: require('./images/blue.png'),
        name: 'Karethium & Astarte',
        region: 'Jewels of Nizam',
        housing: 'Ps',
        services: 'Bd',
        pool: 'Ba',
        area: '185 m2',
        beach: '500 m',
        period: '20.11.19-31.11.19',
        price: 2800,
    },
    {
        id: 5,
        img: require('./images/blue.png'),
        name: 'Karethium & Astarte',
        region: 'Jewels of Nizam',
        housing: 'Ps',
        services: 'Bd',
        pool: 'Ba',
        area: '185 m2',
        beach: '500 m',
        period: '20.11.19-31.11.19',
        price: 2800,
    },
    {
        id: 6,
        img: require('./images/blue.png'),
        name: 'Karethium & Astarte',
        region: 'Jewels of Nizam',
        housing: 'Ps',
        services: 'Bd',
        pool: 'Ba',
        area: '185 m2',
        beach: '500 m',
        period: '20.11.19-31.11.19',
        price: 2800,
    }
]

export default hotelsData